wiki_search_homepage:
    resource: '@WikiSearchBundle/Controller/SearchFormController.php'
    type: annotation

app:
    resource: '@WikiSearchBundle/Controller/SearchController.php'
    type: annotation