wiki_search_homepage:
    resource: '@WikiSearchBundle/Controller/SearchFormController.php'
    type: annotation

app:
    resource: '@WikiSearchBundle/Controller/SearchController.php'
    type: annotation
    
error_redirect:
    resource: '@WikiSearchBundle/Controller/ErrorController.php'
    type: annotation